apiVersion: v1
kind: PersistentVolume
metadata:
    name: demo-persistent-volume
spec:
    capacity:
        storage: 128M
    accessModes:
        - ReadWriteOnce
    hostPath:
        path: /data/demo-persistent-volume 